version: '3.8'

services:
  site_nginx:
    container_name: html_site
    build:
      context: ./ 
    restart: unless-stopped
    volumes:
      - ./html_site/index.html:/usr/share/nginx/html/index.html
      - ./html_site/images/:/usr/share/nginx/html/images
      - ./html_site/assets/:/usr/share/nginx/html/assets
    expose:
      - '80'  # Expose port 80 on the internal network