version: '3.8'

services:
  nginx_proxy_manager:
    container_name: nginx-proxy-manager
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'    # Public HTTP
      - '81:81'    # Public Admin Interface
      - '443:443'  # Public HTTPS
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
        #- ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      public:
        ipv4_address: 192.168.1.10  # Static IP for the nginx_proxy_manager service
      internal:
        ipv4_address: 192.168.2.10

  site_nginx:
    container_name: html_site
    build:
      context: ./html_site  # Set the build context to html_site
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: 192.168.2.20  # Static IP for the site_nginx service
    volumes:
      - ./html_site/index.html:/usr/share/nginx/html/index.html
      - ./html_site/images/:/usr/share/nginx/html/images
      - ./html_site/assets/:/usr/share/nginx/html/assets
    expose:
      - '80'  # Expose port 80 on the internal network
        
  portainer_agent:
    image: portainer/agent:2.21.2
    container_name: portainer_agent
    restart: always
    ports:
      - '9001:9001'  # Expose port 9001 for the Portainer Agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      public:
        ipv4_address: 192.168.1.30  # Static IP for the Portainer service

networks:
  public:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24  # Adjust the subnet as necessary
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24  # Internal subnet for your services
